/**
 * Source of truth for the icon adapter system.
 *
 * Maps every canonical frosted-ui icon name to the semantically-equivalent
 * export of each supported icon library. `null` means the library has no
 * equivalent; the adapter simply omits that name and the registry falls back
 * gracefully (see `src/icons/registry.tsx`).
 *
 * After editing, run `bun run generate:icon-adapters` (packages/frosted-ui).
 * The generator validates every export name against the installed libraries
 * and regenerates `src/icons/adapters/*.ts` plus the `CANONICAL_ICON_NAMES`
 * union in `src/icons/types.ts`.
 */

export const ICON_LIBRARIES = ['lucide', 'phosphor', 'heroicons', 'tabler', 'hugeicons'] as const;

export type IconLibrary = (typeof ICON_LIBRARIES)[number];

/** The module each library's icon exports are imported from (and validated against). */
export const LIBRARY_MODULES: Record<IconLibrary, string> = {
  lucide: 'lucide-react',
  phosphor: '@phosphor-icons/react',
  heroicons: '@heroicons/react/24/outline',
  tabler: '@tabler/icons-react',
  hugeicons: '@hugeicons/core-free-icons',
};

/** The export name of the icon in each library, or `null` when unavailable. */
export type IconMapEntry = { [L in IconLibrary]: string | null };

export const ICON_MAP = {
  AlertCircle: {
    lucide: 'CircleAlert',
    phosphor: 'WarningCircle',
    heroicons: 'ExclamationCircleIcon',
    tabler: 'IconAlertCircle',
    hugeicons: 'AlertCircleIcon',
  },
  Archive: {
    lucide: 'Archive',
    phosphor: 'Archive',
    heroicons: 'ArchiveBoxIcon',
    tabler: 'IconArchive',
    hugeicons: 'ArchiveIcon',
  },
  ArrowDown: {
    lucide: 'ArrowDown',
    phosphor: 'ArrowDown',
    heroicons: 'ArrowDownIcon',
    tabler: 'IconArrowDown',
    hugeicons: 'ArrowDown02Icon',
  },
  ArrowLeft: {
    lucide: 'ArrowLeft',
    phosphor: 'ArrowLeft',
    heroicons: 'ArrowLeftIcon',
    tabler: 'IconArrowLeft',
    hugeicons: 'ArrowLeft02Icon',
  },
  ArrowRight: {
    lucide: 'ArrowRight',
    phosphor: 'ArrowRight',
    heroicons: 'ArrowRightIcon',
    tabler: 'IconArrowRight',
    hugeicons: 'ArrowRight02Icon',
  },
  ArrowUp: {
    lucide: 'ArrowUp',
    phosphor: 'ArrowUp',
    heroicons: 'ArrowUpIcon',
    tabler: 'IconArrowUp',
    hugeicons: 'ArrowUp02Icon',
  },
  AtSign: {
    lucide: 'AtSign',
    phosphor: 'At',
    heroicons: 'AtSymbolIcon',
    tabler: 'IconAt',
    hugeicons: 'AtIcon',
  },
  Battery: {
    lucide: 'BatteryFull',
    phosphor: 'BatteryFull',
    heroicons: 'Battery100Icon',
    tabler: 'IconBattery4',
    hugeicons: 'BatteryFullIcon',
  },
  Bell: {
    lucide: 'Bell',
    phosphor: 'Bell',
    heroicons: 'BellIcon',
    tabler: 'IconBell',
    hugeicons: 'Notification03Icon',
  },
  Bookmark: {
    lucide: 'Bookmark',
    phosphor: 'BookmarkSimple',
    heroicons: 'BookmarkIcon',
    tabler: 'IconBookmark',
    hugeicons: 'Bookmark01Icon',
  },
  Brush: {
    lucide: 'Paintbrush',
    phosphor: 'PaintBrush',
    heroicons: 'PaintBrushIcon',
    tabler: 'IconBrush',
    hugeicons: 'PaintBrush01Icon',
  },
  Bug: {
    lucide: 'Bug',
    phosphor: 'Bug',
    heroicons: 'BugAntIcon',
    tabler: 'IconBug',
    hugeicons: 'Bug01Icon',
  },
  Calendar: {
    lucide: 'Calendar',
    phosphor: 'Calendar',
    heroicons: 'CalendarIcon',
    tabler: 'IconCalendar',
    hugeicons: 'Calendar03Icon',
  },
  Camera: {
    lucide: 'Camera',
    phosphor: 'Camera',
    heroicons: 'CameraIcon',
    tabler: 'IconCamera',
    hugeicons: 'Camera01Icon',
  },
  Check: {
    lucide: 'Check',
    phosphor: 'Check',
    heroicons: 'CheckIcon',
    tabler: 'IconCheck',
    hugeicons: 'Tick02Icon',
  },
  ChevronDown: {
    lucide: 'ChevronDown',
    phosphor: 'CaretDown',
    heroicons: 'ChevronDownIcon',
    tabler: 'IconChevronDown',
    hugeicons: 'ArrowDown01Icon',
  },
  ChevronLeft: {
    lucide: 'ChevronLeft',
    phosphor: 'CaretLeft',
    heroicons: 'ChevronLeftIcon',
    tabler: 'IconChevronLeft',
    hugeicons: 'ArrowLeft01Icon',
  },
  ChevronRight: {
    lucide: 'ChevronRight',
    phosphor: 'CaretRight',
    heroicons: 'ChevronRightIcon',
    tabler: 'IconChevronRight',
    hugeicons: 'ArrowRight01Icon',
  },
  ChevronUp: {
    lucide: 'ChevronUp',
    phosphor: 'CaretUp',
    heroicons: 'ChevronUpIcon',
    tabler: 'IconChevronUp',
    hugeicons: 'ArrowUp01Icon',
  },
  Clock: {
    lucide: 'Clock',
    phosphor: 'Clock',
    heroicons: 'ClockIcon',
    tabler: 'IconClock',
    hugeicons: 'Clock01Icon',
  },
  Close: {
    lucide: 'X',
    phosphor: 'X',
    heroicons: 'XMarkIcon',
    tabler: 'IconX',
    hugeicons: 'Cancel01Icon',
  },
  Cloud: {
    lucide: 'Cloud',
    phosphor: 'Cloud',
    heroicons: 'CloudIcon',
    tabler: 'IconCloud',
    hugeicons: 'CloudIcon',
  },
  Code: {
    lucide: 'Code',
    phosphor: 'Code',
    heroicons: 'CodeBracketIcon',
    tabler: 'IconCode',
    hugeicons: 'CodeIcon',
  },
  Copy: {
    lucide: 'Copy',
    phosphor: 'Copy',
    heroicons: 'DocumentDuplicateIcon',
    tabler: 'IconCopy',
    hugeicons: 'Copy01Icon',
  },
  CreditCard: {
    lucide: 'CreditCard',
    phosphor: 'CreditCard',
    heroicons: 'CreditCardIcon',
    tabler: 'IconCreditCard',
    hugeicons: 'CreditCardIcon',
  },
  Database: {
    lucide: 'Database',
    phosphor: 'Database',
    heroicons: 'CircleStackIcon',
    tabler: 'IconDatabase',
    hugeicons: 'DatabaseIcon',
  },
  DotsHorizontal: {
    lucide: 'Ellipsis',
    phosphor: 'DotsThree',
    heroicons: 'EllipsisHorizontalIcon',
    tabler: 'IconDots',
    hugeicons: 'MoreHorizontalIcon',
  },
  DotsVertical: {
    lucide: 'EllipsisVertical',
    phosphor: 'DotsThreeVertical',
    heroicons: 'EllipsisVerticalIcon',
    tabler: 'IconDotsVertical',
    hugeicons: 'MoreVerticalIcon',
  },
  Download: {
    lucide: 'Download',
    phosphor: 'DownloadSimple',
    heroicons: 'ArrowDownTrayIcon',
    tabler: 'IconDownload',
    hugeicons: 'Download01Icon',
  },
  Edit: {
    lucide: 'Pencil',
    phosphor: 'PencilSimple',
    heroicons: 'PencilIcon',
    tabler: 'IconPencil',
    hugeicons: 'PencilEdit02Icon',
  },
  ExternalLink: {
    lucide: 'ExternalLink',
    phosphor: 'ArrowSquareOut',
    heroicons: 'ArrowTopRightOnSquareIcon',
    tabler: 'IconExternalLink',
    hugeicons: 'LinkSquare02Icon',
  },
  Eye: {
    lucide: 'Eye',
    phosphor: 'Eye',
    heroicons: 'EyeIcon',
    tabler: 'IconEye',
    hugeicons: 'ViewIcon',
  },
  EyeOff: {
    lucide: 'EyeOff',
    phosphor: 'EyeSlash',
    heroicons: 'EyeSlashIcon',
    tabler: 'IconEyeOff',
    hugeicons: 'ViewOffSlashIcon',
  },
  File: {
    lucide: 'File',
    phosphor: 'File',
    heroicons: 'DocumentIcon',
    tabler: 'IconFile',
    hugeicons: 'File01Icon',
  },
  Filter: {
    lucide: 'Funnel',
    phosphor: 'Funnel',
    heroicons: 'FunnelIcon',
    tabler: 'IconFilter',
    hugeicons: 'FilterIcon',
  },
  Flag: {
    lucide: 'Flag',
    phosphor: 'Flag',
    heroicons: 'FlagIcon',
    tabler: 'IconFlag',
    hugeicons: 'Flag01Icon',
  },
  Flame: {
    lucide: 'Flame',
    phosphor: 'Fire',
    heroicons: 'FireIcon',
    tabler: 'IconFlame',
    hugeicons: 'FireIcon',
  },
  Folder: {
    lucide: 'Folder',
    phosphor: 'Folder',
    heroicons: 'FolderIcon',
    tabler: 'IconFolder',
    hugeicons: 'Folder01Icon',
  },
  Gift: {
    lucide: 'Gift',
    phosphor: 'Gift',
    heroicons: 'GiftIcon',
    tabler: 'IconGift',
    hugeicons: 'GiftIcon',
  },
  Globe: {
    lucide: 'Globe',
    phosphor: 'Globe',
    heroicons: 'GlobeAltIcon',
    tabler: 'IconWorld',
    hugeicons: 'GlobalIcon',
  },
  Hash: {
    lucide: 'Hash',
    phosphor: 'Hash',
    heroicons: 'HashtagIcon',
    tabler: 'IconHash',
    hugeicons: 'HashIcon',
  },
  Heart: {
    lucide: 'Heart',
    phosphor: 'Heart',
    heroicons: 'HeartIcon',
    tabler: 'IconHeart',
    hugeicons: 'FavouriteIcon',
  },
  HelpCircle: {
    lucide: 'CircleQuestionMark',
    phosphor: 'Question',
    heroicons: 'QuestionMarkCircleIcon',
    tabler: 'IconHelpCircle',
    hugeicons: 'HelpCircleIcon',
  },
  Home: {
    lucide: 'House',
    phosphor: 'House',
    heroicons: 'HomeIcon',
    tabler: 'IconHome',
    hugeicons: 'Home01Icon',
  },
  Image: {
    lucide: 'Image',
    phosphor: 'Image',
    heroicons: 'PhotoIcon',
    tabler: 'IconPhoto',
    hugeicons: 'Image01Icon',
  },
  Inbox: {
    lucide: 'Inbox',
    phosphor: 'Tray',
    heroicons: 'InboxIcon',
    tabler: 'IconInbox',
    hugeicons: 'InboxIcon',
  },
  Info: {
    lucide: 'Info',
    phosphor: 'Info',
    heroicons: 'InformationCircleIcon',
    tabler: 'IconInfoCircle',
    hugeicons: 'InformationCircleIcon',
  },
  Key: {
    lucide: 'Key',
    phosphor: 'Key',
    heroicons: 'KeyIcon',
    tabler: 'IconKey',
    hugeicons: 'Key01Icon',
  },
  LayoutGrid: {
    lucide: 'LayoutGrid',
    phosphor: 'SquaresFour',
    heroicons: 'Squares2X2Icon',
    tabler: 'IconLayoutGrid',
    hugeicons: 'GridViewIcon',
  },
  Link: {
    lucide: 'Link',
    phosphor: 'Link',
    heroicons: 'LinkIcon',
    tabler: 'IconLink',
    hugeicons: 'Link01Icon',
  },
  List: {
    lucide: 'List',
    phosphor: 'ListBullets',
    heroicons: 'ListBulletIcon',
    tabler: 'IconList',
    hugeicons: 'LeftToRightListBulletIcon',
  },
  Lock: {
    lucide: 'Lock',
    phosphor: 'Lock',
    heroicons: 'LockClosedIcon',
    tabler: 'IconLock',
    hugeicons: 'SquareLock02Icon',
  },
  LogIn: {
    lucide: 'LogIn',
    phosphor: 'SignIn',
    heroicons: 'ArrowLeftEndOnRectangleIcon',
    tabler: 'IconLogin',
    hugeicons: 'Login01Icon',
  },
  LogOut: {
    lucide: 'LogOut',
    phosphor: 'SignOut',
    heroicons: 'ArrowRightStartOnRectangleIcon',
    tabler: 'IconLogout',
    hugeicons: 'Logout01Icon',
  },
  Mail: {
    lucide: 'Mail',
    phosphor: 'Envelope',
    heroicons: 'EnvelopeIcon',
    tabler: 'IconMail',
    hugeicons: 'Mail01Icon',
  },
  MapPin: {
    lucide: 'MapPin',
    phosphor: 'MapPin',
    heroicons: 'MapPinIcon',
    tabler: 'IconMapPin',
    hugeicons: 'MapPinIcon',
  },
  Menu: {
    lucide: 'Menu',
    phosphor: 'List',
    heroicons: 'Bars3Icon',
    tabler: 'IconMenu2',
    hugeicons: 'Menu01Icon',
  },
  Message: {
    lucide: 'MessageCircle',
    phosphor: 'ChatCircle',
    heroicons: 'ChatBubbleOvalLeftIcon',
    tabler: 'IconMessageCircle',
    hugeicons: 'BubbleChatIcon',
  },
  Mic: {
    lucide: 'Mic',
    phosphor: 'Microphone',
    heroicons: 'MicrophoneIcon',
    tabler: 'IconMicrophone',
    hugeicons: 'Mic01Icon',
  },
  Minus: {
    lucide: 'Minus',
    phosphor: 'Minus',
    heroicons: 'MinusIcon',
    tabler: 'IconMinus',
    hugeicons: 'MinusSignIcon',
  },
  Moon: {
    lucide: 'Moon',
    phosphor: 'Moon',
    heroicons: 'MoonIcon',
    tabler: 'IconMoon',
    hugeicons: 'Moon02Icon',
  },
  Package: {
    lucide: 'Package',
    phosphor: 'Package',
    heroicons: 'CubeIcon',
    tabler: 'IconPackage',
    hugeicons: 'PackageIcon',
  },
  Palette: {
    lucide: 'Palette',
    phosphor: 'Palette',
    heroicons: 'SwatchIcon',
    tabler: 'IconPalette',
    hugeicons: 'PaintBoardIcon',
  },
  Paperclip: {
    lucide: 'Paperclip',
    phosphor: 'Paperclip',
    heroicons: 'PaperClipIcon',
    tabler: 'IconPaperclip',
    hugeicons: 'AttachmentIcon',
  },
  Pause: {
    lucide: 'Pause',
    phosphor: 'Pause',
    heroicons: 'PauseIcon',
    tabler: 'IconPlayerPause',
    hugeicons: 'PauseIcon',
  },
  Phone: {
    lucide: 'Phone',
    phosphor: 'Phone',
    heroicons: 'PhoneIcon',
    tabler: 'IconPhone',
    hugeicons: 'CallIcon',
  },
  Play: {
    lucide: 'Play',
    phosphor: 'Play',
    heroicons: 'PlayIcon',
    tabler: 'IconPlayerPlay',
    hugeicons: 'PlayIcon',
  },
  Plus: {
    lucide: 'Plus',
    phosphor: 'Plus',
    heroicons: 'PlusIcon',
    tabler: 'IconPlus',
    hugeicons: 'PlusSignIcon',
  },
  Printer: {
    lucide: 'Printer',
    phosphor: 'Printer',
    heroicons: 'PrinterIcon',
    tabler: 'IconPrinter',
    hugeicons: 'PrinterIcon',
  },
  Refresh: {
    lucide: 'RefreshCw',
    phosphor: 'ArrowsClockwise',
    heroicons: 'ArrowPathIcon',
    tabler: 'IconRefresh',
    hugeicons: 'RefreshIcon',
  },
  Scissors: {
    lucide: 'Scissors',
    phosphor: 'Scissors',
    heroicons: 'ScissorsIcon',
    tabler: 'IconScissors',
    hugeicons: 'ScissorIcon',
  },
  Search: {
    lucide: 'Search',
    phosphor: 'MagnifyingGlass',
    heroicons: 'MagnifyingGlassIcon',
    tabler: 'IconSearch',
    hugeicons: 'Search01Icon',
  },
  Send: {
    lucide: 'Send',
    phosphor: 'PaperPlaneTilt',
    heroicons: 'PaperAirplaneIcon',
    tabler: 'IconSend',
    hugeicons: 'SentIcon',
  },
  Server: {
    lucide: 'Server',
    phosphor: 'HardDrives',
    heroicons: 'ServerIcon',
    tabler: 'IconServer',
    hugeicons: 'ServerStack01Icon',
  },
  Settings: {
    lucide: 'Settings',
    phosphor: 'Gear',
    heroicons: 'Cog6ToothIcon',
    tabler: 'IconSettings',
    hugeicons: 'Settings01Icon',
  },
  Share: {
    lucide: 'Share',
    phosphor: 'ShareNetwork',
    heroicons: 'ShareIcon',
    tabler: 'IconShare',
    hugeicons: 'Share01Icon',
  },
  Shield: {
    lucide: 'Shield',
    phosphor: 'Shield',
    heroicons: 'ShieldCheckIcon',
    tabler: 'IconShield',
    hugeicons: 'Shield01Icon',
  },
  ShoppingCart: {
    lucide: 'ShoppingCart',
    phosphor: 'ShoppingCart',
    heroicons: 'ShoppingCartIcon',
    tabler: 'IconShoppingCart',
    hugeicons: 'ShoppingCart01Icon',
  },
  Sliders: {
    lucide: 'SlidersHorizontal',
    phosphor: 'Sliders',
    heroicons: 'AdjustmentsHorizontalIcon',
    tabler: 'IconAdjustmentsHorizontal',
    hugeicons: 'PreferenceHorizontalIcon',
  },
  Smile: {
    lucide: 'Smile',
    phosphor: 'Smiley',
    heroicons: 'FaceSmileIcon',
    tabler: 'IconMoodSmile',
    hugeicons: 'SmileIcon',
  },
  Star: {
    lucide: 'Star',
    phosphor: 'Star',
    heroicons: 'StarIcon',
    tabler: 'IconStar',
    hugeicons: 'StarIcon',
  },
  Sun: {
    lucide: 'Sun',
    phosphor: 'Sun',
    heroicons: 'SunIcon',
    tabler: 'IconSun',
    hugeicons: 'Sun03Icon',
  },
  Tag: {
    lucide: 'Tag',
    phosphor: 'Tag',
    heroicons: 'TagIcon',
    tabler: 'IconTag',
    hugeicons: 'Tag01Icon',
  },
  Terminal: {
    lucide: 'Terminal',
    phosphor: 'Terminal',
    heroicons: 'CommandLineIcon',
    tabler: 'IconTerminal',
    hugeicons: 'CommandLineIcon',
  },
  ThumbsDown: {
    lucide: 'ThumbsDown',
    phosphor: 'ThumbsDown',
    heroicons: 'HandThumbDownIcon',
    tabler: 'IconThumbDown',
    hugeicons: 'ThumbsDownIcon',
  },
  ThumbsUp: {
    lucide: 'ThumbsUp',
    phosphor: 'ThumbsUp',
    heroicons: 'HandThumbUpIcon',
    tabler: 'IconThumbUp',
    hugeicons: 'ThumbsUpIcon',
  },
  Trash: {
    lucide: 'Trash2',
    phosphor: 'Trash',
    heroicons: 'TrashIcon',
    tabler: 'IconTrash',
    hugeicons: 'Delete02Icon',
  },
  Trophy: {
    lucide: 'Trophy',
    phosphor: 'Trophy',
    heroicons: 'TrophyIcon',
    tabler: 'IconTrophy',
    hugeicons: 'ChampionIcon',
  },
  Truck: {
    lucide: 'Truck',
    phosphor: 'Truck',
    heroicons: 'TruckIcon',
    tabler: 'IconTruck',
    hugeicons: 'TruckIcon',
  },
  Unlock: {
    lucide: 'LockOpen',
    phosphor: 'LockOpen',
    heroicons: 'LockOpenIcon',
    tabler: 'IconLockOpen',
    hugeicons: 'SquareUnlock02Icon',
  },
  Upload: {
    lucide: 'Upload',
    phosphor: 'UploadSimple',
    heroicons: 'ArrowUpTrayIcon',
    tabler: 'IconUpload',
    hugeicons: 'Upload01Icon',
  },
  User: {
    lucide: 'User',
    phosphor: 'User',
    heroicons: 'UserIcon',
    tabler: 'IconUser',
    hugeicons: 'UserIcon',
  },
  Users: {
    lucide: 'Users',
    phosphor: 'Users',
    heroicons: 'UsersIcon',
    tabler: 'IconUsers',
    hugeicons: 'UserMultiple02Icon',
  },
  Video: {
    lucide: 'Video',
    phosphor: 'VideoCamera',
    heroicons: 'VideoCameraIcon',
    tabler: 'IconVideo',
    hugeicons: 'Video01Icon',
  },
  Volume: {
    lucide: 'Volume2',
    phosphor: 'SpeakerHigh',
    heroicons: 'SpeakerWaveIcon',
    tabler: 'IconVolume',
    hugeicons: 'VolumeHighIcon',
  },
  VolumeOff: {
    lucide: 'VolumeX',
    phosphor: 'SpeakerX',
    heroicons: 'SpeakerXMarkIcon',
    tabler: 'IconVolumeOff',
    hugeicons: 'VolumeOffIcon',
  },
  Warning: {
    lucide: 'TriangleAlert',
    phosphor: 'Warning',
    heroicons: 'ExclamationTriangleIcon',
    tabler: 'IconAlertTriangle',
    hugeicons: 'Alert02Icon',
  },
  Wifi: {
    lucide: 'Wifi',
    phosphor: 'WifiHigh',
    heroicons: 'WifiIcon',
    tabler: 'IconWifi',
    hugeicons: 'WifiIcon',
  },
  Zap: {
    lucide: 'Zap',
    phosphor: 'Lightning',
    heroicons: 'BoltIcon',
    tabler: 'IconBolt',
    hugeicons: 'ZapIcon',
  },
} as const satisfies Record<string, IconMapEntry>;

type MappedCanonicalName = keyof typeof ICON_MAP;
